site_name: Proyecto Final
dev_addr: 127.0.0.1:8002
# site_url: 
# repo_url: 
# repo_name: <i class="fa fa-git"></i>

theme:
    name: mkdocs
    custom_dir: resources/
extra_css:
    - css/page.css
nav:
    - Problema: Propuesta.md
    - Requerimientos:
        - Requerimientos del usuario: requerimientos/RequerimientosUsuario.md
        - Requerimientos del sistema: requerimientos/RequerimientosSistema.md
        - Requerimientos del sistema de software: 
            - Requerimientos funcionales: requerimientos/RequerimientosFuncionales.md
            - Requerimientos no funcionales: requerimientos/RequerimientosNoFuncionales.md
        - Especificaciones del software: requerimientos/EspecificacionSoftware.md
    - Ingeniería de requerimientos:
        - Estudio de vialidad: IngenieriaRequerimientos/EstudioVialidad.md
        - Elicitación o extracción: IngenieriaRequerimientos/Elicitacion_Extraccion.md    
    - Modelado:
        - Modelos de software: modelado/Modelado.md
    - Diseño: 
        - Arquitectura: Diseño/Arquitectura.md
        - Componentes: Diseño/Componentes.md
        - Implementacion: Diseño/Implementacion.md
        - Interfaz: Diseño/Interfaz.md
    - Validación:
        - Inicio: todo.md
copyright: ©GMDXX
site_author: GMDXX
